# Generated by Django 3.1.7 on 2021-03-06 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('tablename', models.CharField(max_length=2, null=True)),
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SeatingPlan',
            fields=[
                ('plan_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ManyToManyField(blank=True, to='seating_plan_manager.Student')),
            ],
        ),
    ]
