# Generated by Django 3.1.7 on 2021-04-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating_plan_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
